title: Learning C++
tagline: A course on learning C++
description: If you want to learn C++ you are in the right place.

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: arm-toolchain-docker-ci     # the name of the repository when it is created for the learner
  repo: arm-toolchain-docker-ci    # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: Create variables
  description: You will learn how to create variables using C++
  event: pull_request.synchronize
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: master
    else:
    - type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md
    
# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
- title: Control program flow
  description: You will learn how to control program flow using C++
  event: status
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
- title: Repeat instructions
  description: You will learn how to repeat instructions using C++
  event: status
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
- title: Create functions
  description: You will learn how to create functions using C++
  event: status
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
- title: Create classes
  description: You will learn how to create classes using C++
  event: status
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

